name: Main Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Packages
        run: npm install
      - name: Build and Deploy
        run: npm run build